Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fuxiu/BenchmarkingSPBv2/overlay_nodes/miner_erc.py", line 94, in run
    w3.eth.sendRawTransaction(raw_txn)
  File "/home/fuxiu/.local/lib/python3.6/site-packages/web3/eth.py", line 275, in sendRawTransaction
    [raw_transaction],
  File "/home/fuxiu/.local/lib/python3.6/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'nonce too low'}

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fuxiu/BenchmarkingSPBv2/overlay_nodes/miner_ctp.py", line 114, in run
    communications.send_message(miner_erc_conn, constants.ERC, ctp_id)
  File "/home/fuxiu/BenchmarkingSPBv2/overlay_nodes/helper/communications.py", line 36, in send_message
    + serialised_msg
BrokenPipeError: [Errno 32] Broken pipe

